# settings for ros_control_boilerplate
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_joint
    - elbow_joint
# The joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# The arm controller
arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_joint
    - elbow_joint
  gains:
    shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1